#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/springBootRest?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=1234
#
#spring.jpa.database=mysql
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
#server.servlet.context-path=/app
#server.port=9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springBootRest?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  servlet:
    context-path: /app
  port: 9000

  springfox:
    documentation:
      swagger-ui:
        enable: true